### ISSUE TITLE
How to correctly decode Lytro raw data to get a light field image?

### ISSUE THREAD

**Issue by Vincentqyw** [hazirbas/light-field-toolbox#1]
Dear Hazirbas ,

I am Vincent Qin, my research interest is depth estimation using light field images. Recently, I try to do some experiments using the Lytro raw data. I use the Light field Matlab Toolbox to decode the raw data(.lfps) to get the big LensletImage, however the quality of the image is quite low.  

Here are details of how I got the image. I mainly use the following functions:
## 1. Decode to get the Corrected image.

``` matlab
[LF, LFMetadata,WhiteImage,CorrectedLensletImage, ...
WhiteImageMetadata, LensletGridModel, DecodeOptions]...
=LFLytroDecodeImage(InputFname);%LF size: 11*11*379*379*3
view=squeeze(LF(6,6,:,:,1:3));  %view size: 379*379*3
```

## 2. Color correction
``` matlab
ColMatrix = reshape(LFMetadata.image.color.ccmRgbToSrgbArray, 3,3);
Gamma=LFMetadata.image.color.gamma;
ColBalance=DecodeOptions.ColourBalance;
Color_CorrectedImage = LFColourCorrect(temp, ColMatrix, ColBalance, Gamma);
```
For more detail, I put the code on my [Github](https://github.com/Vincentqyw/light-field-TB/blob/master/Demo.m)

In the following, I put the central view of the LensletImage(scene: Beers) before and after color correction. 
![](http://oofx6tpf6.bkt.clouddn.com/17-11-21/66869289.jpg)

![](http://oofx6tpf6.bkt.clouddn.com/17-11-21/31567281.jpg)

My question is how can I get the high quality image like lytro desktop software.

Thanks!

**Comment by hazirbas** [comment]
Hi,
You can use the lytro toolbox to extract the full resolution images, however, there is no open source code to decode the light fields high quality. Their algorithm is not public.

Cheers,
Caner
